[package]
name = "linux_client"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.15.7", features = ["bluetoothd"] }
futures = "0.3.26"
tokio = { version = "1", features = ["macros", "rt"] }
